### ISSUE TITLE
Loop de jogadas nao atualizada corretamente

### ISSUE THREAD

**Issue by lightniing1** [lightniing1/trabalho-inf008-genius#1]
Na vez do jogador, o loop da função Jogadas não atualiza corretamente se não tiver algo saindo no console (uma mensagem, por exemplo), impedindo de passar a vez para o computador.

Para reproduzir, execute o jogo normalmente.
Para consertar, adicione `System.out.println("teste")` antes da linha `if(contagem == indice1)` ou antes do `for (int x = 0; x < indice1; x++)`. 

Versão do jdk: 16.0.2
IDE: 2021-09 (4.21.0)

**Comment by VictorBohana** [comment]
Resolvido.
