### ISSUE TITLE
Adicionar sistema de pontuação para o jogo

### ISSUE THREAD

**Issue by lightniing1** [lightniing1/trabalho-inf008-genius#2]
Adiciona um sistema simples de pontuação para o jogo.
A função deve exibir no final do jogo uma janela com a pontuação do jogo corrente e a pontuação maxima alcançada.

Bonus: Exibir a pontuação em tempo real. Exigirá algumas modificações na UI.
Podemos talvez exibir a pontuação no titulo da janela do jogo.

**Comment by VictorBohana** [comment]
Resolvido. Já está mostrando a pontuação no final e em tempo real no título da janela do jogo.
