### ISSUE TITLE
Adicionar a possibilidade de mais de um pessoa poder jogar

### ISSUE THREAD

**Issue by lightniing1** [lightniing1/trabalho-inf008-genius#4]
O jogo deve permitir que mais de uma pessoa possa jogar. 
No jogo, caso uma pessoa errar a sequência na sua vez, encerra a partida dela e mostrando sua pontuação. O jogo deve continuar para os jogares restantes.

No final do jogo, deve exibir uma janela contendo:

Numero de jogadores:
Total de jogadas;
Tempo da partida;
Jogada mais rápida;

**Comment by VictorBohana** [comment]
Parcialmente pronta, falta fazer a parte da GUI para inicializar os jogadores.
